name: Build And Push Images to Dockerhub

on:
  push:
    tags:
      - 'v*'

jobs:
  build_docker_images:
    name: Build Docker Images To Dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: 
          - runner
          - teste
          
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{ matrix.dockerfile }}
          tags: |
            type=semver,pattern={{version}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.dockerfile }}
          file: ./${{ matrix.dockerfile }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
