
name: Build And Push Images to Dockerhub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},value=v${{major}}.${{minor}}
            type=semver,pattern={{major}},value=v${{major}}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
