name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_VERSION: 0.0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfile
          file: ./Dockerfile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/runner-azure:${{ github.event.inputs.docker_image_tag }}