#NAME
name: Build and Push Imagens to Dockerhub

#EVENT
on:
  push:
    tags:
      - 'v*'
jobs:
  build_docker_images:
    name: Build Docker Image To Dockerhub
    runs-on: [ubuntu-latest]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        
      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DH_REPO_NAME}}
          tags: |
            type=semver,pattern={{version}}
            
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfile
          file: ./Dockerfile/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
